import test from 'node:test';
import assert from 'node:assert/strict';
import {units,decimal,price} from '../packages/core/money.mjs';
import {initialState,balance,quote,authorize,deposit,reconcile} from '../packages/core/demo.mjs';
import {sampleQR} from '../packages/core/fixtures.mjs';
const now=1788740000000;
const q=()=>quote(sampleQR('USD'),null,now);
test('Exact decimal conversion avoids float arithmetic',()=>{assert.equal(units('0.1')+units('0.2'),units('0.3'));assert.equal(decimal(1n),'0.000001');});
test('Money rejects negatives, exponent, comma, NaN and extra precision',()=>{for(const v of ['-1','1e3','1,000','NaN','0.1234567','Infinity'])assert.throws(()=>units(v));});
test('Fixed demo FX and fee are exact',()=>assert.deepEqual(price('4.50','USD'),{base:'4.500000',fee:'0.113500',total:'4.613500',rate:'1',feeLabel:'0,10 USDT + 0,3%',demo:true}));
test('VND round UP to atomic unit',()=>{assert.equal(price('125000','VND').base,'4.901961');});
test('No payment for zero amount',()=>assert.throws(()=>price('0','USD')));
test('Immutable amount from QR',()=>assert.throws(()=>quote(sampleQR(), '9',now),/Không thể sửa/));
test('Static QR accepts user amount',()=>assert.equal(quote(sampleQR('STATIC'),'7.20',now).total,'7.321600'));
test('Initial demo balance',()=>assert.equal(balance(initialState()),'250.000000'));
test('Success debits available and empties hold',()=>{const {state,transaction}=authorize(initialState(),q(),'123456','SUCCESS',now);assert.equal(balance(state),'245.386500');assert.equal(balance(state,'USER_HELD'),'0.000000');assert.equal(transaction.status,'SUCCESS');});
test('Failed payment releases all held funds',()=>{const {state}=authorize(initialState(),q(),'123456','FAILED',now);assert.equal(balance(state),'250.000000');assert.equal(balance(state,'USER_HELD'),'0.000000');});
test('Unknown payment holds funds; reconciliation success finalizes',()=>{const r=authorize(initialState(),q(),'123456','UNKNOWN',now);assert.equal(balance(r.state),'245.386500');assert.equal(balance(r.state,'USER_HELD'),'4.613500');const done=reconcile(r.state,r.transaction.id,'SUCCESS');assert.equal(balance(done.state),'245.386500');assert.equal(balance(done.state,'USER_HELD'),'0.000000');});
test('Unknown payment can release on definitive failure once only',()=>{const r=authorize(initialState(),q(),'123456','UNKNOWN',now);const done=reconcile(r.state,r.transaction.id,'FAILED');assert.equal(balance(done.state),'250.000000');assert.throws(()=>reconcile(done.state,r.transaction.id,'FAILED'));});
test('Same quote is idempotent',()=>{const quoted=q(),r=authorize(initialState(),quoted,'123456','SUCCESS',now);const duplicate=authorize(r.state,quoted,'123456','SUCCESS',now);assert.equal(duplicate.transaction.id,r.transaction.id);assert.equal(duplicate.state.ledger.length,r.state.ledger.length);});
test('Insufficient balance cannot debit',()=>{assert.throws(()=>authorize(initialState(),quote(sampleQR('STATIC'),'999',now),'123456','SUCCESS',now),/chưa đủ/);});
test('Quote expiry checked at confirmation',()=>assert.throws(()=>authorize(initialState(),q(),'123456','SUCCESS',now+120000),/hết hạn/));
test('Modified quote total rejected',()=>{const quoted=q();quoted.total='0.000001';assert.throws(()=>authorize(initialState(),quoted,'123456','SUCCESS',now),/không hợp lệ/);});
test('PIN retries cause temporary lockout without debit',()=>{let s=initialState();for(let i=0;i<5;i++)s=authorize(s,q(),'000000','SUCCESS',now).state;assert.equal(balance(s),'250.000000');assert.throws(()=>authorize(s,q(),'123456','SUCCESS',now+1),/chờ 30/);assert.equal(authorize(s,q(),'123456','SUCCESS',now+31000).transaction.status,'SUCCESS');});
test('Demo deposit uses exact units and caps amounts',()=>{assert.equal(balance(deposit(initialState(),'0.000001').state),'250.000001');assert.throws(()=>deposit(initialState(),'10001'));});
test('Ledger entries conserve total across all accounts',()=>{let s=initialState();s=authorize(s,q(),'123456','SUCCESS',now).state;const accounts=new Set(s.ledger.flatMap(e=>[e.from,e.to]));assert.equal([...accounts].reduce((sum,a)=>sum+BigInt(balance(s,a).replace('.','')),0n),0n);});
test('Do not resubmit same QR while its result is unknown',()=>{const r=authorize(initialState(),q(),'123456','UNKNOWN',now);assert.throws(()=>authorize(r.state,q(),'123456','SUCCESS',now),/chờ đối soát/);});
