import test from 'node:test';
import assert from 'node:assert/strict';
import { crc16,decodeQR,tlv } from '../packages/core/qr.mjs';
import { sampleQR,field,finish } from '../packages/core/fixtures.mjs';
const now=1788740000000;
test('CRC-16/CCITT-FALSE published check value',()=>assert.equal(crc16('123456789'),'29B1'));
for(const [type,currency] of [['USD','USD'],['KHR','KHR'],['VND','VND'],['STATIC','USD'],['DYNAMIC','USD']]) test(`Decode ${type} synthetic fixture`,()=>{const q=decodeQR(sampleQR(type,now),now);assert.equal(q.currency,currency);assert.equal(q.amount,type==='STATIC'?null:type==='VND'?'125000':type==='KHR'?'20000':'4.50');assert.equal(q.isValid,true);});
test('Independent VietQR fixture from xuannghia-derived public example',()=>{const q=decodeQR('00020101021138540010A00000072701240006970418011062540463830208QRIBFTTA53037045802VN6304AB32');assert.equal(q.account,'6254046383');assert.equal(q.bank,'970418');assert.equal(q.amount,null);});
test('Reject amount changed with old CRC',()=>assert.throws(()=>decodeQR(sampleQR().replace('4.50','9.50')),/CRC/));
test('Reject truncated QR',()=>assert.throws(()=>decodeQR(sampleQR().slice(0,-2))));
test('Reject duplicate top-level tag',()=>assert.throws(()=>decodeQR(finish(sampleQR().slice(0,-8)+field('53','840'))),/trùng/));
test('Reject invalid TLV length',()=>assert.throws(()=>tlv('0010abc')));
test('Reject duplicate nested tag',()=>assert.throws(()=>tlv(field('00','x')+field('00','y')),/trùng/));
test('CRC must be last',()=>assert.throws(()=>decodeQR(sampleQR()+field('80','a'))));
test('Reject unsupported payload / links',()=>assert.throws(()=>decodeQR('https://example.com')));
test('Reject expired dynamic KHQR',()=>assert.throws(()=>decodeQR(sampleQR('DYNAMIC',now),now+300001),/hết hạn/));
test('Reject dynamic QR missing amount',()=>{const s=sampleQR('DYNAMIC',now).slice(0,-8).replace(field('54','4.50'),'');assert.throws(()=>decodeQR(finish(s),now),/thiếu số tiền/);});
test('Reject dynamic KHQR without expiry',()=>{const s=sampleQR().slice(0,-8).replace('010211','010212');assert.throws(()=>decodeQR(finish(s)),/thiếu hạn/);});
test('Unknown tags preserved',()=>{const q=decodeQR(finish(sampleQR().slice(0,-8)+field('80','UNKNOWN')));assert.equal(q.tags['80'],'UNKNOWN');});
test('Reject decimal VND and zero amounts',()=>{assert.throws(()=>decodeQR(finish(sampleQR('VND').slice(0,-8).replace(field('54','125000'),field('54','1.5')))));assert.throws(()=>decodeQR(finish(sampleQR().slice(0,-8).replace(field('54','4.50'),field('54','0')))));});
test('VNPayQR preview only',()=>{const raw=finish(field('00','01')+field('01','11')+field('26',field('00','A000000775')+field('01','DEMO'))+field('53','704')+field('58','VN'));const q=decodeQR(raw);assert.equal(q.scheme,'VNPAYQR');assert.equal(q.payable,false);});
